# Generated by Django 5.0.7 on 2024-08-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('source_word', 'target_word', 'dictionary'), name='unique_word_in_dictionary'),
        ),
    ]
